### ISSUE TITLE
Using a Locally Built WebRTC，This file is not produced: webrtc_<version>_headers.zip

### ISSUE THREAD

**Issue by ffdsss** [wireapp/wire-avs#38]
Hi，I'm using a locally built WebRTC, no headers.zip file is generated, only android.zip. please how can i solve it

**Comment by mythsunwind** [comment]
You can find how we build webrtc in the pipeline script here: https://github.com/wireapp/prebuilt-webrtc-binaries/blob/main/Jenkinsfile.groovy#L20

Use the docker file to build it yourself but be aware that this takes quite a while...
